# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8083}
    context-path: /auth/
    use-forward-headers: true
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript
# PROFILES
spring:
    application.name: auth-service
    profiles.active: prod
# EUREKA
eureka:
#  instance:
#      hostname: localhost
#      port: 8081
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      defaultZone: http://discovery-service:8081/eureka/
# LOGGING
logging.level.org.springframework.security: DEBUG
