# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8083}
    context-path: /auth/
    use-forward-headers: true
    error.whitelabel.enabled: false
# PROFILES
spring:
    application.name: shardis-auth
    profiles.active: prod
# EUREKA
eureka:
  instance:
      hostname: localhost
      port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
# LOGGING
logging.level.org.springframework.security: DEBUG
